/**
 * Compresses default hero source images and generates blur placeholders for LCP.
 * Run: npx tsx scripts/optimize-hero-images.ts
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import {
  HOMEPAGE_HERO_IMAGE_DEFAULT,
  defaultPageHeroImages,
} from "../src/config/page-images";
import { heroFeatureCards } from "../src/config/hero";

const ROOT = process.cwd();
const PUBLIC_DIR = path.join(ROOT, "public");
const BLUR_OUTPUT = path.join(ROOT, "src/lib/hero-blur-data.ts");

const HERO_WIDTH = 1920;
const HERO_QUALITY = 82;
const BLUR_WIDTH = 16;

function collectHeroPaths(): string[] {
  const paths = new Set<string>([
    HOMEPAGE_HERO_IMAGE_DEFAULT,
    ...Object.values(defaultPageHeroImages),
    ...heroFeatureCards.map((card) => card.image),
    "/images/pexels-mike-van-schoonderwalt-1884800-5505119.jpg",
  ]);

  return [...paths].filter((src) => src.startsWith("/") && !src.startsWith("http"));
}

async function optimizeImage(relativePath: string) {
  const filePath = path.join(PUBLIC_DIR, relativePath.replace(/^\//, ""));
  if (!fs.existsSync(filePath)) {
    console.warn(`skip missing: ${relativePath}`);
    return null;
  }

  const before = fs.statSync(filePath).size;
  const image = sharp(filePath);
  const metadata = await image.metadata();

  let pipeline = image.rotate();
  if ((metadata.width ?? 0) > HERO_WIDTH) {
    pipeline = pipeline.resize({ width: HERO_WIDTH, withoutEnlargement: true });
  }

  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".png") {
    await pipeline.png({ compressionLevel: 9, palette: true }).toFile(`${filePath}.tmp`);
  } else {
    await pipeline.jpeg({ quality: HERO_QUALITY, mozjpeg: true }).toFile(`${filePath}.tmp`);
  }

  fs.renameSync(`${filePath}.tmp`, filePath);
  const after = fs.statSync(filePath).size;
  console.log(
    `optimized ${relativePath}: ${Math.round(before / 1024)}KB -> ${Math.round(after / 1024)}KB`,
  );

  return filePath;
}

async function generateBlur(filePath: string) {
  const buffer = await sharp(filePath)
    .resize(BLUR_WIDTH, undefined, { withoutEnlargement: true })
    .jpeg({ quality: 40 })
    .toBuffer();

  return `data:image/jpeg;base64,${buffer.toString("base64")}`;
}

async function main() {
  const heroPaths = collectHeroPaths();
  const blurMap: Record<string, string> = {};

  for (const relativePath of heroPaths) {
    const optimizedPath = await optimizeImage(relativePath);
    if (!optimizedPath) continue;
    blurMap[relativePath] = await generateBlur(optimizedPath);
  }

  const fileContents = `// Generated by scripts/optimize-hero-images.ts — do not edit manually.
export const heroBlurDataBySrc: Record<string, string> = ${JSON.stringify(blurMap, null, 2)};
`;

  fs.writeFileSync(BLUR_OUTPUT, fileContents, "utf8");
  console.log(`wrote ${Object.keys(blurMap).length} blur placeholders to ${BLUR_OUTPUT}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
